Repository everli/design-system-frontend, pull requests merged in 2023-09, with the labels that each got.

#102 Changelog 0.1.16
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready-for-code-review

#103 production 0.1.16
  .gitignore
  CHANGELOG.md
  README.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  scripts/version.js
  src/components/Icon/ico-categories.vue
  src/components/Icon/ico-stores.vue
Labels: release

#105 Changelog 0.1.17
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready-for-code-review

#104 [FEAT] Update stores and search icon
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-search.vue
  src/components/Icon/ico-stores.vue
Labels: patch, ready-for-code-review

#106 production 0.1.17
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/ico-search.vue
  src/components/Icon/ico-stores.vue
Labels: release

#107 [FEAT] Add new padlock icons
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-padlock-close.vue
  src/components/Icon/ico-padlock-open.vue
Labels: ready-for-code-review

#108 [FIX] Fix dependencies security issues
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
Labels: minor, ready-for-code-review

#109 Changelog 0.1.18
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready-for-code-review

#110 Production: 0.1.18
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/ico-padlock-close.vue
  src/components/Icon/ico-padlock-open.vue
Labels: release

#111 chore: ignore scripts preinstal
  README.md
  package.json
Labels: patch, ready-for-code-review
