Repository everli/design-system-frontend, pull requests merged in 2024-06, with the labels that each got.

#138 [FIX] Hub - update profile icon build
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-profile.vue
Labels: patch, ready-for-code-review

#137 [DC-368] Add ico-stores-outline icon
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-stores-outline.vue
  src/components/Icon/icons.json
Labels: patch, ready-for-code-review

#139 [DC-404] Add ico-position-mark-filled-hub
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-position-mark-filled-hub.vue
  src/components/Icon/icons.json
Labels: patch, ready-for-code-review

#140 [FEAT] Add new arrow/x bold icons
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-add-bold.vue
  src/components/Icon/ico-arrow-down-bold.vue
  src/components/Icon/ico-arrow-left-bold.vue
  src/components/Icon/ico-arrow-right-bold.vue
  src/components/Icon/ico-arrow-up-bold.vue
  src/components/Icon/ico-x-bold.vue
  src/components/Icon/icons.json
Labels: patch, ready-for-code-review

#141 changelog: 2.4.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready-for-code-review

#142 production: 0.2.4
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/ico-add-bold.vue
  src/components/Icon/ico-arrow-down-bold.vue
  src/components/Icon/ico-arrow-left-bold.vue
  src/components/Icon/ico-arrow-right-bold.vue
  src/components/Icon/ico-arrow-up-bold.vue
  src/components/Icon/ico-position-mark-filled-hub.vue
  src/components/Icon/ico-profile.vue
  src/components/Icon/ico-stores-outline.vue
  src/components/Icon/ico-x-bold.vue
  src/components/Icon/icons.json
Labels: release
