Repository everli/design-system-frontend, pull requests merged in 2024-05, with the labels that each got.

#124 [DC-370] Add new icons (hub)
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/getIconNames.js
  src/components/Icon/ico-arrow-down.vue
  src/components/Icon/ico-arrow-left-new.vue
  src/components/Icon/ico-arrow-right-new.vue
  src/components/Icon/ico-arrow-top-new.vue
  src/components/Icon/ico-categories.vue
  src/components/Icon/ico-chevron-down-new.vue
  src/components/Icon/ico-chevron-left-new.vue
  src/components/Icon/ico-chevron-right-new.vue
  src/components/Icon/ico-chevron-top-new.vue
  src/components/Icon/ico-clock-filled-new.vue
  src/components/Icon/ico-eye-hyde.vue
  src/components/Icon/ico-eye-show.vue
  src/components/Icon/ico-flash-new.vue
  src/components/Icon/ico-for-you-filled.vue
  src/components/Icon/ico-for-you.vue
  src/components/Icon/ico-local.vue
  src/components/Icon/ico-menu-new.vue
  src/components/Icon/ico-offer-filled.vue
  src/components/Icon/ico-offer.vue
  src/components/Icon/ico-profile.vue
  src/components/Icon/ico-search-new.vue
  src/components/Icon/ico-selected-filled.vue
  src/components/Icon/ico-selected.vue
  src/components/Icon/ico-speciality-filled.vue
  src/components/Icon/ico-speciality.vue
  src/components/Icon/ico-supermarkets-filled.vue
  src/components/Icon/ico-supermarkets.vue
  src/components/Icon/icons.json
Labels: minor, ready-for-code-review

#125 changelog: 0.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready-for-code-review

#126 production: 0.2.0
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/getIconNames.js
  src/components/Icon/ico-arrow-down.vue
  src/components/Icon/ico-arrow-left-new.vue
  src/components/Icon/ico-arrow-right-new.vue
  src/components/Icon/ico-arrow-top-new.vue
  src/components/Icon/ico-categories.vue
  src/components/Icon/ico-chevron-down-new.vue
  src/components/Icon/ico-chevron-left-new.vue
  src/components/Icon/ico-chevron-right-new.vue
  src/components/Icon/ico-chevron-top-new.vue
  src/components/Icon/ico-clock-filled-new.vue
  src/components/Icon/ico-eye-hyde.vue
  src/components/Icon/ico-eye-show.vue
  src/components/Icon/ico-flash-new.vue
  src/components/Icon/ico-for-you-filled.vue
  src/components/Icon/ico-for-you.vue
  src/components/Icon/ico-local.vue
  src/components/Icon/ico-menu-new.vue
  src/components/Icon/ico-offer-filled.vue
  src/components/Icon/ico-offer.vue
  src/components/Icon/ico-profile.vue
  src/components/Icon/ico-search-new.vue
  src/components/Icon/ico-selected-filled.vue
  src/components/Icon/ico-selected.vue
  src/components/Icon/ico-speciality-filled.vue
  src/components/Icon/ico-speciality.vue
  src/components/Icon/ico-supermarkets-filled.vue
  src/components/Icon/ico-supermarkets.vue
  src/components/Icon/icons.json
Labels: release

#127 [FEAT] Adjust icon names add more hub icons
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-foryou-filled.vue
  src/components/Icon/ico-foryou-outline.vue
  src/components/Icon/ico-menu-hub.vue
  src/components/Icon/ico-menu-new.vue
  src/components/Icon/ico-offers-filled.vue
  src/components/Icon/ico-offers-outline.vue
  src/components/Icon/ico-profile.vue
  src/components/Icon/ico-selected-outline.vue
  src/components/Icon/ico-speciality-outline.vue
  src/components/Icon/ico-supermarkets-outline.vue
  src/components/Icon/icons.json
  src/styles/generic/_colors.scss
  src/styles/settings/_colors.scss
Labels: minor, ready-for-code-review

#129 Production 0.2.1-tmac
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/ico-foryou-filled.vue
  src/components/Icon/ico-foryou-outline.vue
  src/components/Icon/ico-menu-hub.vue
  src/components/Icon/ico-menu-new.vue
  src/components/Icon/ico-offers-filled.vue
  src/components/Icon/ico-offers-outline.vue
  src/components/Icon/ico-profile.vue
  src/components/Icon/ico-selected-outline.vue
  src/components/Icon/ico-speciality-outline.vue
  src/components/Icon/ico-supermarkets-outline.vue
  src/components/Icon/icons.json
  src/styles/generic/_colors.scss
  src/styles/settings/_colors.scss
Labels: release

#132 production: 0.2.2
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/ico-account-filled.vue
  src/components/Icon/ico-account.vue
  src/components/Icon/ico-flash-filled.vue
  src/components/Icon/ico-orders.vue
  src/components/Icon/ico-payments.vue
  src/components/Icon/icons.json
Labels: release

#134 [FEAT] Add new color (coral-100) and icon ogo-everli-plus-horizontal-long
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/icons.json
  src/components/Icon/logo-everli-plus-horizontal-long.vue
  src/styles/generic/_colors.scss
  src/styles/settings/_colors.scss
Labels: patch, ready-for-code-review

#133 [DC-368] Add icons for new navigation menu
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  src/components/Icon/ico-gift-filled.vue
  src/components/Icon/icons.json
  src/components/Icon/logo-android.vue
  src/components/Icon/logo-everli-app.vue
Labels: patch, ready-for-code-review

#135 Changelog 0.2.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: ready-for-code-review

#136 production: 0.2.3
  CHANGELOG.md
  dist/everli.common.js
  dist/everli.common.js.map
  dist/everli.umd.js
  dist/everli.umd.js.map
  dist/everli.umd.min.js
  dist/everli.umd.min.js.map
  dist/library/everli.common.js
  dist/library/everli.common.js.map
  dist/library/everli.umd.js
  dist/library/everli.umd.js.map
  dist/library/everli.umd.min.js
  dist/library/everli.umd.min.js.map
  package-lock.json
  package.json
  src/components/Icon/ico-gift-filled.vue
  src/components/Icon/icons.json
  src/components/Icon/logo-android.vue
  src/components/Icon/logo-everli-app.vue
  src/components/Icon/logo-everli-plus-horizontal-long.vue
  src/styles/generic/_colors.scss
  src/styles/settings/_colors.scss
Labels: release
